language: node_js
node_js:
- "8"
- "stable"
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - node_modules

before_install:
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - tests/scripts/setup_linux_env.sh
  - sleep 2

after_script:
- echo "code-championship-blocks build complete"
